name: ZombieApocalypse
version: '1.0BestFullUpdate'
main: io.unfish.zombieapocalypse.Main
api-version: 1.16
softdepend: [ EssentialsX ]
authors: [ unfish ]
description: Create a zombie apocalypse in minecraft world
commands:
  bloodmoon:
    description: Start/Stop bloodmoon event